### ISSUE TITLE
Date Type and Builder

### ISSUE THREAD

**Issue by jonasliendl** [jonasliendl/zeiten#2]
Developers using this library should be able to easily create dates. Therefore, we introduce a Date Type which can be used for all functions within the library. This Date type can be created by a Date Builder which is used to easily create Dates by providing either detailed information about, date, time, and timezone, or a time string, or a number.

**To-Dos**
- [ ] Date Type with detailed information about date, time, and timezone
- [ ] Date Builder → Use builder pattern to build dates
- [ ] Convert a string or number into date type
- [ ] Documentation of functions, types, and structs.
