### ISSUE TITLE
Date and time manipulations

### ISSUE THREAD

**Issue by jonasliendl** [jonasliendl/zeiten#3]
Developers should be able to manipulate the time, date, and timezone of a date object.

**To-Dos**
- [ ] Manipulate time (add and remove: hours, minutes, seconds, milliseconds)
- [ ] Manipulate date (add and remove: days, weeks, quarters, months, years)
- [ ] Manipulate timezone (change time zone, or remove current [will default to UTC])
- [ ] Add documentation
